### ISSUE TITLE
1.19.4, plugin kick players from server without any errors in console 

### ISSUE THREAD

**Issue by kjakkonrad** [LoreSchaeffer/CustomF3Brand#1]
![image](https://github.com/LoreSchaeffer/CustomF3Brand/assets/121307335/dd57d706-1f00-4972-b665-93e339dcef1c)

**Comment by LoreSchaeffer** [comment]
Hi, can you provide me more context about the issue. Where's the plugin (spigot or forks or bungeecord or forks), version of the plugin and, if possible, the list of the plugins

**Comment by kjakkonrad** [comment]
paper 1.19.4 (last build +-). Ver. pl. 1.1.0 and latest from SpigotMC. May help, I updated the server from 1.19.3 to 1.19.4.  The plugin stopped working after the update, and it kicks out players when trying to join the server. It was difficult to locate the problem because it does not display any logs in the console and the only thing that can be done is to remove it step by step.

**Comment by kjakkonrad** [comment]
I can't provide a list of plugins, and jars. I have a few plugins of my own.

**Comment by LoreSchaeffer** [comment]
The latest version is 1.1.3 and you can find it either on spigot or modrinth. I suggest using modrinth that is updated more frequently.
https://modrinth.com/plugin/customf3brand/version/1.1.3

**Comment by kjakkonrad** [comment]
I updated it, still the same (spigotmc). the plugin is not stable, I can't risk blocking the server again.
