### ISSUE TITLE
Add Velocity support

### ISSUE THREAD

**Issue by mrjasonn** [LoreSchaeffer/CustomF3Brand#2]

**Comment by LoreSchaeffer** [comment]
I released the first alpha for velocity. You can find it here: https://modrinth.com/plugin/customf3brand/version/1.2.0
Let me know if you encounter any issue.

**Comment by LoreSchaeffer** [comment]
I have to intercept the packet from the backend servers because you can have the plugin both on spigot and bungeecord/velocity and if you have an animated text they must be updated together in spigot an bungeecord/velocity

**Comment by LoreSchaeffer** [comment]
It's lightweight, it injects a PacketDecoder directly in the netty pipeline that intercepts only the brand packet. The injection is done in the same way of protocolize. Regarding the compatibility I've tried some commonly used plugins and I haven't noticed any problem. But I don't drive a velocity server so I don't have the numbers to test it properly
