### ISSUE TITLE
Error in console occurred in onPacketSending

### ISSUE THREAD

**Issue by Alien0-7** [LoreSchaeffer/CustomF3Brand#3]
Hi, I have a problem with the latest version of the plugin (1.1.4). When i change gamemode it gives me [this](https://pastebin.com/VteFMsVN) error in console, and [this](https://pastebin.com/M5xhUkV5) when i change world

**Comment by LoreSchaeffer** [comment]
Hi, I haven't been able to reproduce your bug, can you give me more details about your server. I need at least the version of ProtocolLib you are using and if you can the list of the plugins. I think that it could be a problem releated to other plugins

**Comment by Alien0-7** [comment]
ProtocolLib: build 679 (latest)
Server: paper 1.20.4 build 408the plugins are [these](https://pastebin.com/frt24n34)

**Comment by LoreSchaeffer** [comment]
I tried to run the server with your version of paper and protocollib and i tested all the plugin you use that require protocollib and I haven't been able to reproduce your bug.

To proceed you can make a copy of your server and try to disable one plugin at a time and see if it works.
If you need more help we could try together in a discord call

**Comment by LoreSchaeffer** [comment]
I've released a new update that should catch a lot of errors, let me know if you have other problems https://modrinth.com/plugin/customf3brand/version/1.2.0

**Comment by Alien0-7** [comment]
It seems to be solved, ty
