### ISSUE TITLE
Error in console when player joins server

### ISSUE THREAD

**Issue by humansouls** [LoreSchaeffer/CustomF3Brand#4]
Getting this error when player joins server
https://pastebin.com/nkzsc4xW

**Comment by LoreSchaeffer** [comment]
Please provide me the version of your server, of the plugin and of ProtocolLib

**Comment by humansouls** [comment]
plugin: last version from modrinth
protocollib build 679 
1.20.4 paper 409

**Comment by LoreSchaeffer** [comment]
I cannot reproduce your bug but I'm adding to the next version of the plugin a way to catch the exception and manage it

**Comment by LoreSchaeffer** [comment]
I released a new update that should catch a lot of errors, let me know if you have other problems https://modrinth.com/plugin/customf3brand/version/1.2.0
