### ISSUE TITLE
Error with packets on 1.20.1, latest version of cf4brand

### ISSUE THREAD

**Issue by Indistoupia** [LoreSchaeffer/CustomF3Brand#5]
![image](https://github.com/LoreSchaeffer/CustomF3Brand/assets/132406054/7e37b55d-c604-4c9e-a3e1-75e83cf332c4)

**Comment by Indistoupia** [comment]
This don't let me entry to the server

**Comment by LoreSchaeffer** [comment]
Please provide more information like the version of the server and other plugins that could interfere. If you have one in your console also a stacktrace would be nice
